name: rexe
version: '0.2'
summary: Synchronous task executor for Mesos
description: |
  Execute container tasks in a Mesos cluster synchronously with STDOUT piped back to the caller.

grade: stable
confinement: classic

parts:
  rexe:
    # See 'snapcraft plugins'
    plugin: rust
    source: .
    build-packages:
      - libssl-dev
apps:
  rexe:
    command: rexe